name: my_manga_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.1
  google_fonts: ^8.0.2  
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  jikan_api: ^2.3.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1
  uuid: ^4.5.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
